import { Router } from 'express';
import prisma from '../prisma';
import { authenticateToken } from '../middleware/auth';
import { requireConversationMember, requireMessageAccess } from '../utils/authz';

const router = Router();
router.post('/todos/:convId', authenticateToken, async (req: any, res) => { try { const convId = parseInt(req.params.convId); if (!(await requireConversationMember(req.userId, convId))) return res.status(403).json({ error: 'Access denied' }); const { text, assignedTo } = req.body; const todo = await prisma.todo.create({ data: { text, assignedTo, conversationId: convId, createdById: req.userId } }); res.json(todo); } catch { res.status(500).json({ error: 'Error' }); } });
router.get('/todos/:convId', authenticateToken, async (req: any, res) => { try { const convId = parseInt(req.params.convId); if (!(await requireConversationMember(req.userId, convId))) return res.status(403).json({ error: 'Access denied' }); const todos = await prisma.todo.findMany({ where: { conversationId: convId }, orderBy: { createdAt: 'desc' } }); res.json(todos); } catch { res.status(500).json({ error: 'Error' }); } });
router.put('/todos/:id/toggle', authenticateToken, async (req: any, res) => { try { const todo = await prisma.todo.findUnique({ where: { id: parseInt(req.params.id) } }); if (!todo) return res.status(404).json({ error: 'Not found' }); if (!(await requireConversationMember(req.userId, todo.conversationId))) return res.status(403).json({ error: 'Access denied' }); const updated = await prisma.todo.update({ where: { id: todo.id }, data: { isDone: !todo.isDone } }); res.json(updated); } catch { res.status(500).json({ error: 'Error' }); } });
router.delete('/todos/:id', authenticateToken, async (req: any, res) => { try { const todo = await prisma.todo.findUnique({ where: { id: parseInt(req.params.id) } }); if (!todo) return res.status(404).json({ error: 'Not found' }); if (!(await requireConversationMember(req.userId, todo.conversationId))) return res.status(403).json({ error: 'Access denied' }); await prisma.todo.delete({ where: { id: todo.id } }); res.json({ success: true }); } catch { res.status(500).json({ error: 'Error' }); } });
router.post('/calendar/:convId', authenticateToken, async (req: any, res) => { try { const convId = parseInt(req.params.convId); if (!(await requireConversationMember(req.userId, convId))) return res.status(403).json({ error: 'Access denied' }); const { title, description, startAt, endAt, isRecurring } = req.body; const event = await prisma.calendarEvent.create({ data: { title, description, startAt: new Date(startAt), endAt: endAt ? new Date(endAt) : null, isRecurring: !!isRecurring, conversationId: convId, createdById: req.userId } }); res.json(event); } catch { res.status(500).json({ error: 'Error' }); } });
router.get('/calendar/:convId', authenticateToken, async (req: any, res) => { try { const convId = parseInt(req.params.convId); if (!(await requireConversationMember(req.userId, convId))) return res.status(403).json({ error: 'Access denied' }); const events = await prisma.calendarEvent.findMany({ where: { conversationId: convId }, orderBy: { startAt: 'asc' } }); res.json(events); } catch { res.status(500).json({ error: 'Error' }); } });
router.delete('/calendar/:id', authenticateToken, async (req: any, res) => { try { const event = await prisma.calendarEvent.findUnique({ where: { id: parseInt(req.params.id) } }); if (!event) return res.status(404).json({ error: 'Not found' }); if (!(await requireConversationMember(req.userId, event.conversationId))) return res.status(403).json({ error: 'Access denied' }); await prisma.calendarEvent.delete({ where: { id: event.id } }); res.json({ success: true }); } catch { res.status(500).json({ error: 'Error' }); } });
router.post('/reminders', authenticateToken, async (req: any, res) => { try { const { messageId, text, remindAt } = req.body; const message = await requireMessageAccess(req.userId, Number(messageId)); if (!message) return res.status(403).json({ error: 'Access denied' }); const reminder = await prisma.reminder.create({ data: { userId: req.userId, messageId, text, remindAt: new Date(remindAt) } }); res.json(reminder); } catch { res.status(500).json({ error: 'Error' }); } });
router.get('/reminders', authenticateToken, async (req: any, res) => { try { const reminders = await prisma.reminder.findMany({ where: { userId: req.userId, isSent: false }, include: { message: { select: { id: true, text: true } } }, orderBy: { remindAt: 'asc' } }); res.json(reminders); } catch { res.status(500).json({ error: 'Error' }); } });
router.delete('/reminders/:id', authenticateToken, async (req: any, res) => { try { const reminder = await prisma.reminder.findUnique({ where: { id: parseInt(req.params.id) } }); if (!reminder || reminder.userId !== req.userId) return res.status(403).json({ error: 'Access denied' }); await prisma.reminder.delete({ where: { id: reminder.id } }); res.json({ success: true }); } catch { res.status(500).json({ error: 'Error' }); } });
router.get('/sessions', authenticateToken, async (req: any, res) => {
  try {
    const sessions = await prisma.session.findMany({
      where: { userId: req.userId },
      select: { id: true, device: true, ip: true, lastUsed: true, createdAt: true },
      orderBy: { lastUsed: 'desc' }
    });
    res.json(sessions.map((session) => ({ ...session, isCurrent: session.id === req.sessionId })));
  } catch { res.status(500).json({ error: 'Error' }); }
});
router.delete('/sessions/:id', authenticateToken, async (req: any, res) => {
  try {
    const session = await prisma.session.findUnique({ where: { id: parseInt(req.params.id) } });
    if (!session || session.userId !== req.userId) return res.status(403).json({ error: 'Access denied' });
    const isCurrent = session.id === req.sessionId;
    await prisma.session.delete({ where: { id: session.id } });
    res.json({ success: true, id: session.id, isCurrent });
  } catch { res.status(500).json({ error: 'Error' }); }
});
router.post('/stars/:messageId', authenticateToken, async (req: any, res) => { try { const messageId = parseInt(req.params.messageId); const message = await requireMessageAccess(req.userId, messageId); if (!message) return res.status(403).json({ error: 'Access denied' }); const existing = await prisma.starredMessage.findFirst({ where: { userId: req.userId, messageId } }); if (existing) { await prisma.starredMessage.delete({ where: { id: existing.id } }); return res.json({ removed: true }); } await prisma.starredMessage.create({ data: { userId: req.userId, messageId } }); res.json({ starred: true }); } catch { res.status(500).json({ error: 'Error' }); } });
router.get('/stars', authenticateToken, async (req: any, res) => { try { const starred = await prisma.starredMessage.findMany({ where: { userId: req.userId }, include: { message: { include: { sender: { select: { id: true, name: true, avatar: true } }, conversation: { select: { id: true, name: true } } } } }, orderBy: { createdAt: 'desc' } }); res.json(starred); } catch { res.status(500).json({ error: 'Error' }); } });
router.post('/highlights', authenticateToken, async (req: any, res) => { try { const { name, cover, storyIds } = req.body; const h = await prisma.storyHighlight.create({ data: { userId: req.userId, name, cover, storyIds: JSON.stringify(storyIds) } }); res.json(h); } catch { res.status(500).json({ error: 'Error' }); } });
router.get('/highlights/:userId', authenticateToken, async (req: any, res) => { try { const highlights = await prisma.storyHighlight.findMany({ where: { userId: parseInt(req.params.userId) }, orderBy: { createdAt: 'desc' } }); res.json(highlights.map(h => ({ ...h, storyIds: JSON.parse(h.storyIds) }))); } catch { res.status(500).json({ error: 'Error' }); } });
router.delete('/highlights/:id', authenticateToken, async (req: any, res) => { try { const h = await prisma.storyHighlight.findUnique({ where: { id: parseInt(req.params.id) } }); if (!h || h.userId !== req.userId) return res.status(403).json({ error: 'Access denied' }); await prisma.storyHighlight.delete({ where: { id: h.id } }); res.json({ success: true }); } catch { res.status(500).json({ error: 'Error' }); } });
export default router;
